//
//  problem2.cpp
//  projecteuler_1
//
//  Created by Nikhil Jain on 10/23/15.
//  Copyright © 2015 Nikhil Jain. All rights reserved.
//




/*
 
 Problem 2
 
 */

//
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#include <iostream>
using namespace std;

int fibonacci(int num) {
    
    if (num == 2 || num == 1)
        return num;
    
    return fibonacci(num - 1) + fibonacci(num - 2);
    
}


int problem2() {
    
    int sum = 0;
    
    for (int i = 1; i <= 4000001; i++)
        sum += fibonacci(i);
    
    cout << sum << endl;
    
    return 0;
}